### ISSUE TITLE
NullPointerException in ChunkLoaderManager

### ISSUE THREAD

**Issue by pahimar** [Chicken-Bones/ChickenChunks#11]
NPE in ChunkLoaderManager. Using Forge 1224 with CodeChickenCore 1.0.4.29 and ChickenChunks 1.3.4.13

> [13:23:02] [Server thread/ERROR]: Encountered an unexpected exception 
> net.minecraft.util.ReportedException: Exception getting block type in world
>   at net.minecraft.world.World.func_147439_a(World.java:354) ~[ahb.class:?]
>   at com.rwtema.extrautils.ExtraUtils$ChunkloadCallback.ticketsLoaded(ExtraUtils.java:1870) ~[ExtraUtils$ChunkloadCallback.class:?]
>   at net.minecraftforge.common.ForgeChunkManager.loadWorld(ForgeChunkManager.java:515) ~[ForgeChunkManager.class:?]
>   at net.minecraftforge.common.ForgeInternalHandler.onDimensionLoad(ForgeInternalHandler.java:64) ~[ForgeInternalHandler.class:?]
>   at cpw.mods.fml.common.eventhandler.ASMEventHandler_6_ForgeInternalHandler_onDimensionLoad_Load.invoke(.dynamic) ~[?:?]
>   at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
>   at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
>   at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:230) ~[MinecraftServer.class:?]
>   at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:258) ~[lt.class:?]
>   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
>   at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
> Caused by: java.lang.NullPointerException
>   at codechicken.chunkloader.ChunkLoaderManager.getPlayerOrganiser(ChunkLoaderManager.java:661) ~[ChunkLoaderManager.class:?]
>   at codechicken.chunkloader.ChunkLoaderManager.getOrganiser(ChunkLoaderManager.java:640) ~[ChunkLoaderManager.class:?]
>   at codechicken.chunkloader.ChunkLoaderManager.addChunkLoader(ChunkLoaderManager.java:631) ~[ChunkLoaderManager.class:?]
>   at codechicken.chunkloader.TileChunkLoaderBase.activate(TileChunkLoaderBase.java:108) ~[TileChunkLoaderBase.class:?]
>   at codechicken.chunkloader.TileChunkLoaderBase.func_145829_t(TileChunkLoaderBase.java:35) ~[TileChunkLoaderBase.class:?]
>   at net.minecraft.world.chunk.Chunk.func_150812_a(Chunk.java:886) ~[apx.class:?]
>   at net.minecraft.world.chunk.Chunk.func_150813_a(Chunk.java:862) ~[apx.class:?]
>   at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:500) ~[aqk.class:?]
>   at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41) ~[ChunkIOProvider.class:?]
>   at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) ~[ChunkIOProvider.class:?]
>   at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) ~[AsynchronousExecutor.class:?]
>   at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) ~[AsynchronousExecutor.class:?]
>   at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) ~[ChunkIOExecutor.class:?]
>   at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) ~[ms.class:?]
>   at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
>   at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
>   at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
>   at net.minecraft.world.World.func_147439_a(World.java:345) ~[ahb.class:?]
>   ... 10 more

**Comment by kevinkjt2000** [comment]
I am getting the same crash on my server only on startup.  If I remove the chicken chunks mod and then boot, shutdown, put the mod back, boot again.  Everything is fine.  Chunkloaders can be placed and they seem to work fine.  But if the server has to reboot it crashes.
I could send you the world but it is pretty big ~1.5 GB zipped with 7z
Anywhere here is the log with the crash appearing on line 40310.
https://gist.github.com/kevinkjt2000/ffa40aeeed752bd7912d/raw/fml-server.log

**Comment by nightstick24** [comment]
Any updates on this? Our server is experiencing the same crash-loop cycle.

log at http://pastebin.com/fKq1hTfm

It's virtually identical to both Kevin and Pahimar's.

**Comment by devryb** [comment]
Same issue here

**Comment by nightstick24** [comment]
Try looking at the Coordinates it provides you with in the full log, From mine:

Details:
        Found chunk: true
        Location: World: (-3871,83,9316), Chunk: (at 1,5,4 in -242,582; contains blocks -3872,0,9312 to -3857,255,9327), Region: (-8,18; contains chunks -256,576 to -225,607, blocks -4096,0,9216 to -3585,255,9727)

It says Location: World, this just means it's in the world it can be in any dimension though. For me this problem was solved by removing an Ender Quarry and Quarry from the Deep Dark. I'd check the coordinates provided in every dimension you have available to you.

**Comment by nightstick24** [comment]
Try looking at the Coordinates it provides you with in the full log, From mine:

Details:
        Found chunk: true
        Location: World: (-3871,83,9316), Chunk: (at 1,5,4 in -242,582; contains blocks -3872,0,9312 to -3857,255,9327), Region: (-8,18; contains chunks -256,576 to -225,607, blocks -4096,0,9216 to -3585,255,9727)

It says Location: World, this just means it's in the world it can be in any dimension though. For me this problem was solved by removing an Ender Quarry and Quarry from the Deep Dark. I'd check the coordinates provided in every dimension you have available to you.

**Comment by nightstick24** [comment]
Try looking at the Coordinates it provides you with in the full log, From mine:

Details:
        Found chunk: true
        Location: World: (-3871,83,9316), Chunk: (at 1,5,4 in -242,582; contains blocks -3872,0,9312 to -3857,255,9327), Region: (-8,18; contains chunks -256,576 to -225,607, blocks -4096,0,9216 to -3585,255,9727)

It says Location: World, this just means it's in the world it can be in any dimension though. For me this problem was solved by removing an Ender Quarry and Quarry from the Deep Dark. I'd check the coordinates provided in every dimension you have available to you.

**Comment by nightstick24** [comment]
Try looking at the Coordinates it provides you with in the full log, From mine:

Details:
        Found chunk: true
        Location: World: (-3871,83,9316), Chunk: (at 1,5,4 in -242,582; contains blocks -3872,0,9312 to -3857,255,9327), Region: (-8,18; contains chunks -256,576 to -225,607, blocks -4096,0,9216 to -3585,255,9727)

It says Location: World, this just means it's in the world it can be in any dimension though. For me this problem was solved by removing an Ender Quarry and Quarry from the Deep Dark. I'd check the coordinates provided in every dimension you have available to you.

**Comment by kevinkjt2000** [comment]
There is an Ender Quarry running in the deep dark on my server.  So that might be part of the problem.

**Comment by devryb** [comment]
For me it was an actual chicken loader. we had to remove the mod from the server and start it up without it to get things running again.  Then added the mod back afterwards.

**Comment by JayWood** [comment]
On my lunch break, had a similar crash when checking in on my server.  http://pastebin.com/fKq1hTfm

Disabling the ChickenChunks mod solves the problem.
Pack: FTB Inifinity 1.5.1
* ChickenChunks 1.7.10-1.3.4.19-universal
* CodeChickenCore 1.0.6.43

To be clear, I did not have to disable CCC, only CC.

Considering the amount of dimensions we have on the server, this can take some time to TP to every one and see if there's a block there, it'd be really nice if the log would specify a dimension :(

**Comment by callous4567** [comment]
Encountering the same issue

Pack : RR3.3
- Chicken Chunks 1.3.4.19
- CodeChickenCore 1.0.7.47

ExtraUtilities related crash.

**Comment by themechman** [comment]
I can confirm this as well has just occurred as well. Opening world in MCEdit and removing ticking entities does not help. Removing chuck loader did not restore.

Removing CC completely and putting it back has permitted proper startup.

**Comment by kevinkjt2000** [comment]
@themechman Don't forget to post versions :)

**Comment by themechman** [comment]
Chicken Chunks 1.3.4.19 and CodeChickenCore 1.0.7.47

It only happened once I'm afraid and I cannot reproduce despite best efforts. I've simply removed extrautil from my mods for now.
