### ISSUE TITLE
Chicken Chunks conflicting with mods that load chunks before the ChunkManager is initialized (ExtraUtils)

### ISSUE THREAD

**Issue by Slind14** [Chicken-Bones/ChickenChunks#28]
```
java.lang.NullPointerException: Exception getting block type in world
	at codechicken.chunkloader.ChunkLoaderManager.getPlayerOrganiser(ChunkLoaderManager.java:659)
	at codechicken.chunkloader.ChunkLoaderManager.getOrganiser(ChunkLoaderManager.java:638)
	at codechicken.chunkloader.ChunkLoaderManager.addChunkLoader(ChunkLoaderManager.java:629)
	at codechicken.chunkloader.TileChunkLoaderBase.activate(TileChunkLoaderBase.java:108)
	at codechicken.chunkloader.TileChunkLoaderBase.func_145829_t(TileChunkLoaderBase.java:35)
	at net.minecraft.world.chunk.Chunk.func_150812_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_150813_a(Chunk.java:963)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:551)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:44)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:164)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:137)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:260)
	at net.minecraft.world.World.func_72964_e(World.java:739)
	at net.minecraft.world.World.func_147439_a(World.java:665)
	at com.rwtema.extrautils.ExtraUtils$ChunkloadCallback.ticketsLoaded(ExtraUtils.java:1881)
	at net.minecraftforge.common.ForgeChunkManager.loadWorld(ForgeChunkManager.java:515)
	at net.minecraftforge.common.ForgeInternalHandler.onDimensionLoad(ForgeInternalHandler.java:64)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_8_ForgeInternalHandler_onDimensionLoad_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:431)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Slind14** [comment]
I don't know if a simple npe check is fine for you, in case: https://github.com/Chicken-Bones/ChickenChunks/pull/29 (the chunk is being force loaded anyways, other possible cc chunks around probably not)

**Comment by Chicken-Bones** [comment]
I just have to check to see if this is an adequate solution, it might result in chicken chunkloaders not working if the original loader is removed
